todo_list/urls.py
from django.urls import path

from todo_list.views import (
    TaskListView, TaskCreateView,
    TaskUpdateView, TaskDeleteView,
    complete_or_undo, TagListView,
    TagCreateView, TagUpdateView,
    TagDeleteView,
)


urlpatterns = [
    path("", TaskListView.as_view(), name="index"),
    path("task/create/", TaskCreateView.as_view(), name="task-create"),
    path("task/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("task/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("task/<int:pk>/complete-or-undo/", complete_or_undo, name="task-complete-or-undo"),

    path("tags", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
]

app_name = "todo-list"

todo_list_task/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo_list.urls", namespace="todo-list")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo_list/models.py
from django.db import models


class Task(models.Model):
    content = models.TextField()
    datetime = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField("Tag", related_name="tasks")

    class Meta:
        ordering = ["is_done", "-datetime"]


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

todo_list/forms.py
from django import forms

from todo_list.models import Task, Tag


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )
    deadline = forms.DateTimeField(
        widget=forms.SelectDateWidget,
        required=False
    )

    class Meta:
        model = Task
        fields = "__all__"

todo_list/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import generic

from todo_list.forms import TaskForm
from todo_list.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task
    template_name = "todo_list/index.html"
    queryset = Task.objects.prefetch_related("tags")


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo-list:index")


class TaskUpdateView(generic.UpdateView):
    queryset = Task.objects.all()
    form_class = TaskForm
    success_url = reverse_lazy("todo-list:index")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo-list:index")


def complete_or_undo(request, pk):
    task = Task.objects.get(pk=pk)
    if task.is_done:
        task.is_done = False
        task.save()
    else:
        task.is_done = True
        task.save()
    return HttpResponseRedirect(reverse_lazy("todo-list:index"))


class TagListView(generic.ListView):
    model = Tag


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo-list:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo-list:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo-list:tag-list")

templates/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
        integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N"
        crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">

  <title>Todo-list</title>

</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-3">

        {% block sidebar %}
          {% include "includes/sidebar.html" %}
        {% endblock %}

      </div>
      <div class="col-sm-7" class="block">
        {% block content %}
        {% endblock %}


      </div>
    </div>
  </div>
</body>
</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a class="sidebar" href="{% url 'todo-list:index' %}">Home page</a></li>
  <li class="list-group-item"><a class="sidebar" href="{% url 'todo-list:tag-list' %}">Tag list</a></li>
</ul>

templates/todo_list/index.html
{% extends "base.html" %}

{% block content %}
  <br>
  <h1>TODO list <a style="float: right" href="{% url 'todo-list:task-create' %}" class="btn btn-primary">Add task</a></h1>
  <br>
  <ul>
    {% for task in task_list %}
      <li>
        <div class="content">
          <p>{{ task.content }}
          {% if task.is_done %} <span style="color: green">Done</span>
            <a style="float: right" class="btn btn-secondary" href="{% url 'todo-list:task-complete-or-undo' pk=task.id %}">Undo</a>
            {% else %}<span style="color: red">Not done</span>
            <a style="float: right" class="btn btn-success" href="{% url 'todo-list:task-complete-or-undo' pk=task.id %}">Complete</a>
          {% endif %}<p>
        </div>

        <div class="timer">
          <p>Created: {{ task.datetime }}
            {% if task.deadline %} <span style="color: brown">Deadline: {{ task.deadline }}</span>{% endif %}</p>
        </div>

        <div class="text-muted">
          <p>Tags: {% for tag in task.tags.all %} {{ tag.name }} {% endfor %}
            <a href="{% url 'todo-list:task-update' pk=task.id %}">Update</a>
            <a href="{% url 'todo-list:task-delete' pk=task.id %}">Delete</a></p>
        </div>
        <hr>
      </li>
    {% endfor %}
  </ul>
{% endblock %}

templates/todo_list/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <p><strong>Confirm to delete this tag ?</strong>

  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes, delete" class="btn btn-danger">
    <a class="btn btn-secondary" href="{% url 'todo-list:tag-list' %}">No, forget</a>
  </form>
{% endblock %}

templates/todo_list/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create new" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo_list/tag_list.html
{% extends "base.html" %}

{% block content %}
  <br>
  <h1>Tags <a class="btn btn-primary" style="float: right" href="{% url 'todo-list:tag-create' %}">Add</a></h1>
  <table class="table">
    <tr>
      <th>Name</th>
      <th>Update</th>
      <th>Delete</th>
    </tr>
    {% for tag in tag_list %}
      <tr>
        <td>
          {{ tag.name }}
        </td>
        <td>
          <a class="btn btn-secondary" href="{% url 'todo-list:tag-update' pk=tag.id %}">Update</a>
        </td>
        <td>
          <a class="btn btn-secondary" href="{% url 'todo-list:tag-delete' pk=tag.id %}">Delete</a>
        </td>
      </tr>
    {% endfor %}
  </table>
{% endblock %}

templates/todo_list/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <p><strong>Confirm to delete this task ?</strong>

  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes, delete" class="btn btn-danger">
    <a class="btn btn-secondary" href="{% url 'todo-list:index' %}">No, forget</a>
  </form>
{% endblock %}

templates/todo_list/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create new" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}